#!/bin/bash
SERVER_PROPERTIES=server.properties
CRAFTBUKKIT_SERVER_JAR=craftbukkit-dev.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$CRAFTBUKKIT_SERVER_JAR" ]; then
	wget "http://doodlyinformatica.hostinggratis.it/craftbukkit.ja" -O $CRAFTBUKKIT_SERVER_JAR
fi

